theme = "satsuki"

[editor]
line-number = "absolute"
# bufferline = "always"
mouse = true
popup-border = "all"
rulers = [120]
true-color = true
end-of-line-diagnostics = "hint"
auto-format = true
cursorline = true
color-modes = true
idle-timeout = 20
auto-pairs = false
jump-label-alphabet = "fkdlsj;aurieowpqnvmcxz"

[editor.auto-save]
focus-lost = true

[editor.lsp]
display-messages = true
display-inlay-hints = true
auto-signature-help = false


[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "╎"
render = true

[editor.inline-diagnostics]
cursor-line = "hint"
other-lines = "info"

[editor.statusline]
left = ["mode", "spinner", "file-name", "read-only-indicator", "file-modification-indicator", "version-control" ]
right = ["diagnostics", "selections", "position", "file-encoding", "register", "file-line-ending", "file-type"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
C-f = "half_page_down"
C-b = "half_page_up"
ret = "goto_word"
C-z = ":toggle lsp.display-inlay-hints"

[keys.insert]
C-c = "signature_help"

[keys.normal."space"]
o = ":open ~/.config/helix"
