[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]
auto-format = true

[[language]]
name = "typescript"
language-servers = [ "typescript-language-server", "vscode-eslint-language-server", "eslint", "tailwindcss-ls" ]
formatter = { command = 'prettierd', args = [".ts"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [ "typescript-language-server" ]
formatter = { command = 'prettierd', args = [".js"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
formatter = { command = 'prettierd', args = [".jsx"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]
formatter = { command = 'prettierd', args = [".tsx"] }
auto-format = true

[[language]]
name = "svelte"
language-servers = [ "tailwindcss-ls", "svelteserver" ]
formatter = { command = 'prettierd', args = [".svelte"] }
auto-format = true

[language-server.astro-ls]
command = "astro-ls"
args = ["--stdio"]
config = {typescript = {tsdk = "/Users/lucas/AppData/Roaming/npm/node_modules/typescript/lib"}, environment = "node"}

[[language]]
name = "astro"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "typescript"] }
language-servers = [ "astro-ls", "tailwindcss-ls" ]
