# SYNTAX HIGHLIGHTING
"attribute" = { fg = "light_brown" }
"type" = { fg = "green" }
"type.builtin" = { fg = "red" }
"type.parameter" = { fg = "white" }
"type.enum" = { fg = "white" }
"type.enum.variant" = { fg = "white" }
"constructor" = { fg = "green" }
"constant" = { fg = "blue" }
"constant.character.escape" = { fg = "yellow" }
"string" = { fg = "light_brown" }
"string.regexp" = { fg = "yellow" }
"comment" = { fg = "comment_gray", modifiers = ["dim"] }
"variable" = { fg = "white" }
"variable.parameter" = { fg = "white" }
"variable.other" = { fg = "purple" }
"variable.other.member" = { fg = "green" }
"label" = { fg = "blue" }
"punctuation" = { fg = "white" }
"punctuation.bracket" = { fg = "white" }
"punctuation.special" = { fg = "yellow" }
"keyword" = { fg = "red" }
"keyword.operator" = { fg = "blue" }
"keyword.directive" = { fg = "white" }
"keyword.function" = { fg = "red" }
"keyword.storage" = { fg = "red" }
"keyword.storage.modifier" = { fg = "green" }
"operator" = { fg = "red" }
"function" = { fg = "blue" }
"function.method" = { fg = "yellow" }
"function.macro" = { fg = "green" }
"function.special" = { fg = "yellow" }
"tag" = { fg = "red" }
"namespace" = { fg = "white" }
"diff" = { fg = "white" }
"diff.minus" = { fg = "red" }
"diff.delta" = { fg = "orange" }

# MARKUP, SYNAX HIGHLIGHTING AND INTERFACE HYBRID
"markup.heading" = { fg = "green" }
"markup.heading.1" = { fg = "crystal_blue", modifiers = ["bold"] }
"markup.heading.2" = { fg = "sky_blue", modifiers = ["bold"] }
"markup.heading.3" = { fg = "dreamy_blue", modifiers = ["bold"] }
"markup.heading.4" = { fg = "crystal_blue" }
"markup.heading.5" = { fg = "sky_blue" }
"markup.heading.6" = { fg = "dreamy_blue" }
"markup.list" = { fg = "red" }
"markup.bold" = { fg = "crystal_blue", modifiers = ["bold"] }
"markup.italic" = { fg = "crystal_blue", modifiers = ["italic"] }
"markup.strikethrough" = { fg = "crystal_blue", modifiers = ["crossed_out"] }
"markup.link" = { fg = "crystal_blue", underline = { color = "yellow", style = "line" } }
"markup.link.url" = { fg = "slate_purple", underline = { color = "slate_purple", style = "line" } }
"markup.link.label" = { fg = "crystal_blue" }
"markup.link.text" = { fg = "crystal_blue", modifiers = ["bold"] }
"markup.quote" = { fg = "winter_sky", modifiers = ["italic"] }
"markup.raw" = { fg = "light_brown" }
"markup.raw.block" = { fg = "white" }

# USER INTERFACE 
"ui.background" = {}                                                               # workspace background
"ui.background.separator" = { fg = "winter_sky" }                                                    # picker separator below input line (space + j)
"ui.gutter" = { bg = "deep_abyss" }                                                                  # gutter
"ui.linenr" = { fg = "slate_gray" }                                                                      # line numbers
"ui.linenr.selected" = { fg = "red", modifiers = ["bold"] }                                              # line number for the line the cursor is on
"ui.statusline" = { fg = "white", bg = "red", modifiers = ["bold"]}                                                      # statusline, fucused
"ui.statusline.inactive" = { fg = "slate_gray", bg = "pitch_black" }                                     # statusline, unfocused
"ui.statusline.normal" = { fg = "deep_abyss", bg = "green", modifiers = ["bold"] }                       # statusline normal mode (if editor.color-modes is enabled)
"ui.statusline.insert" = { fg = "deep_abyss", bg = "purple", modifiers = ["bold"] }                      # statusline insert mode (if editor.color-modes is enabled)
"ui.statusline.select" = { fg = "deep_abyss", bg = "blue", modifiers = ["bold"] }                        # statusline select mode (if editor.color-modes is enabled)
"ui.statusline.separator" = { fg = "winter_sky" }                                                        # separator character is statusline
"ui.bufferline" = { fg = "slate_gray", modifiers = ["bold"] }                                            # bufferline inactive tab
"ui.bufferline.active" = { fg = "winter_sky", bg = "faded_red" }                                         # bufferline active tab
"ui.bufferline.background" = { bg = "pitch_black" }                                                      # bufferline background
"ui.virtual.ruler" = { bg = "midnight_thunder" }                                                         # ruler columns
"ui.virtual.whitespace" = { fg = "faded_gray" }                                                          # whitespace characters
"ui.virtual.indent-guide" = { fg = "faded_gray" }                                                        # vertical indent width guides
"ui.virtual.inlay-hint" = { fg = "purple" }                                                              # inlay hints of all kinds
"ui.virtual.inlay-hint.parameter" = { fg = "slate_gray" }                                                # inlay hints of kind parameter (lsps are not required to set a kind)
"ui.virtual.inlay-hint.type" = { fg = "blue" }                                                           # inlay hints of kind type (lsps are not required to set a kind)
"ui.virtual.wrap" = { fg = "slate_gray" }                                                                # soft-wrap indicator
"ui.virtual.jump-label" = { modifiers = ["reversed"] }                                                   # virtual jump labels (g + w)
"ui.selection" = { bg = "selection_light" }                                                                    # slave selections in the editing area
"ui.selection.primary" = { bg = "selection_blue" }                                                            # primary selection in the editing area
"ui.cursor" = { modifiers = ["reversed"] }                                                               # only if "ui.cursor.primary.normal" isn't set
"ui.cursor.normal" = { fg = "winter_sky", bg = "twilight_blue" }                                         # slave cursor block in normal mode
"ui.cursor.insert" = { bg = "rustic_red" }                                                               # slave cursor block in insert mode
"ui.cursor.select" = { bg = "deep_purple" }                                                            # slave cursor block in select mode
"ui.cursor.match" = { fg = "white", bg = "deep_purple", modifiers = ["bold"] }                           # matching bracket etc
"ui.cursor.primary" = { modifiers = ["reversed"] }                                                       # cursor with primary selection (has no effect due to "ui.cursor.primary.normal" is set)
"ui.cursor.primary.normal" = { fg = "deep_abyss", bg = "red" }                                           # cursor block in normal mode
"ui.cursor.primary.insert" = { fg = "deep_abyss", bg = "ruby_glow" }                                     # cursor block in insert mode
"ui.cursor.primary.select" = { fg = "winter_sky", bg = "deep_purple" }                                   # cursor block in select mode (not the selected color)
"ui.cursorline.primary" = { bg = "blue_gray" }                                                           # line of the primary cursor
"ui.cursorline.secondary" = { bg = "midnight_thunder"}                                                   # lines of secondary cursors
"ui.cursorcolumn.primary" = { bg = "nightfall_blue" }                                                    # column of the primary cursor
"ui.cursorcolumn.secondary" = { bg = "midnight_thunder" }                                                # columns of secondary cursors

# USER INTERFACE - MENUS AND POPUP
"ui.popup" = { fg = "winter_sky", bg = "midnight_thunder" }                                              # documentation popups (space + k)
"ui.popup.info" = { fg = "winter_sky", bg = "midnight_thunder" }                                         # prompt for multiple key options, menu border (space, g, z, m, etc)
"ui.window" = { fg = "slate_gray" }                                                                      # borderlines separating splits
"ui.help" = { fg = "winter_sky", bg = "midnight_thunder" }                                               # description box for commands
"ui.text" = { fg = "white" }                                                                             # default text style, command prompts, popup text, etc
"ui.text.focus" = { fg = "dreamy_blue" }                                                                 # the currently selected line in the picker (space j, space f, space s, etc)
"ui.text.inactive" = { fg = "slate_gray" }                                                               # same as ui.text but when the text is inactive e.g. suggestions
"ui.text.info" = { fg = "winter_sky", bg = "midnight_thunder" }                                          # the key: command in ui.popup.info boxes (space, g, z, m, etc)
"ui.menu" = { fg = "winter_sky", bg = "midnight_thunder" }                                               # code and command completion menus ":"
"ui.menu.selected" = { fg = "winter_sky", bg = "blue" }                                      # selected autocomplete item
"ui.menu.scroll" = { fg = "faded_red", bg = "moonlight_ocean" }                                          # scrollbar
"ui.highlight" = { underline = { color = "sky_blue", style = "line" } }                                  # highlighted lines in the picker preview
# USER INTERFACE - DIAGNOSTICS

"warning" = { fg = "lemon_zest" }                                                                        # diagnostics warning (gutter)
"error" = { fg = "ruby_glow" }                                                                           # diagnostics error (gutter)
"info" = { fg = "sky_blue" }                                                                             # diagnostics info (gutter)
"hint" = { fg = "walnut_brown" }                                                                         # diagnostics hint (gutter)
"diagnostic" = { modifiers = ["reversed"] }                                                              # diagnostics fallback style (editing area)
"diagnostic.hint" = { fg = "deep_abyss", bg = "walnut_brown" }                                           # diagnostics hint (editing area)
"diagnostic.info" = { fg = "winter_sky", bg = "twilight_blue" }                                          # diagnostics info (editing area)
"diagnostic.warning" = { fg = "winter_sky", bg = "rustic_amber" }                                        # diagnostics warning (editing area)
"diagnostic.error" = { fg = "winter_sky", bg = "faded_red" }                                            # diagnostics error (editing area)

# COLOR NAMES
[palette] 
# PALETTE USER INTERFACE
deep_abyss = "#242729"
stormy_night = "#254862"
nightfall_blue = "#1f2937"
midnight_thunder = "#0d1526"
twilight_blue = "#2c5484"
pitch_black = "#000000"
winter_sky = "#f3f4f6"
slate_gray = "#838a97"
blaze_orange = "#ff9000"
lemon_zest = "#ffba00"
leafy_green = "#81be83"
dreamy_blue = "#6eb0ff"
crystal_blue = "#99c7ff"
sky_blue = "#45b1e8"
moonlight_ocean = "#0c1420"
rustic_red = "#540b0c"
ruby_glow = "#fa7970"
walnut_brown = "#987654"
rustic_amber = "#9d5800"
slate_purple = "#d2a8ff"
light_purple = "#7533bd"
deep_purple = "#4c1785"
faded_red = "#5d2626"
faded_gray = "#878b91"
blue_gray = "#2b3944"
selection_blue = "#014961"
selection_light = "#4d4d07"
comment_gray = "#c6fc12"

# SYNTAX HIGHLIGHTING
black = "#0d1117"
red = "#E24A3E"
green = "#46F263"
yellow = "#e4ff10"
orange = "#ff9000"
blue = "#6893F3"
purple = "#d2a8ff"
brown = "#987654"
gray = "#596570"
white = "#F8F8F2"
light_brown = "#f6e9cb"
dark_red = "#330603"
pink = "#ff00dd"
